"""Backward-compatible re-exports — prefer src.services.todos."""

from src.db.connection import (
    ensure_db,
    get_data_dir,
    get_db_connection,
    get_db_path,
    init_db,
    migrate_db,
)
from src.services.todos import (
    PRIORITIES,
    ListFilters,
    TodoRecord,
    create_todo,
    fetch_open_todos_for_planning,
    fetch_stats_snapshot,
    fetch_todos,
    format_due_date,
    get_category_id,
    get_category_name,
    get_db_connection,
    get_todo_completed,
    list_category_names,
    search_todos,
    search_todos_single,
    update_todo,
    validate_due_date,
)

__all__ = [
    "PRIORITIES",
    "ListFilters",
    "TodoRecord",
    "create_todo",
    "ensure_db",
    "fetch_open_todos_for_planning",
    "fetch_stats_snapshot",
    "fetch_todos",
    "format_due_date",
    "get_category_id",
    "get_category_name",
    "get_data_dir",
    "get_db_connection",
    "get_db_path",
    "get_todo_completed",
    "init_db",
    "list_category_names",
    "migrate_db",
    "search_todos",
    "search_todos_single",
    "update_todo",
    "validate_due_date",
]
